### ISSUE TITLE
Better document and handle credential usage

### ISSUE THREAD

**Issue by nichtich** [maxlath/wikidata-agent#2]
After installation, username and password must be typed at:

```
prompt:
prompt:
```

This should better be `username:` and `password:` instead. With wrong credentials `npm start` results in a stack track instead of a more clear error message such as "Login failed. The supplied credentials could not be authenticated." (this is hidden somewhere in the error output).

The README does not tell how to set credentials after installation. This can be done with 

```
./scripts/postinstall
```

It would be useful to also check credentials in this script.

**Comment by maxlath** [comment]
@nichtich hey, sorry for the much delayed answer, somehow I wasn't watching the repo oO
I can't give it much time at the moment but PRs are very welcome. If it's an issue, moving from coffee to js can be considered
