### ISSUE TITLE
Avoid duplicated creation of claims

### ISSUE THREAD

**Issue by nichtich** [maxlath/wikidata-agent#3]
By default, the agent **should always check whether a claim already exists** to avoid duplicate creation of claims! If the new claim _is equal to_ an existing claim, or if it _is included by_ an existing claim, the agent should return HTTP 302 (Found) and not change anything. If the new claim _includes_ an existing claim, the existing claim should be updated instead of creating a new claim and the agent should return HTTP 200 (OK).
- claim A and B are equal if they shares same entity, property, value, rank, references, and qualifiers.
- claim A includes claim B if both share same entity, property, value, and rank, but the set of qualifiers in A is a superset of qualifiers in B and/or the set of references in A is a superset of the set of references in B. 

The agent may further check whether a new claim conflicts with an existing claim but this may more likely be wanted by the user. The user may also want to modify an existing claim instead. Anyway, conflicting claims are another issue.

**Comment by maxlath** [comment]
I gave it a shot with e0ca03a. I went with returning a 400 error code when existing as, afaik, 302 is associated to temporary redirection rather than "this content already exist"
